### ISSUE TITLE
Sagat Cant Be Beat In Story Mode So YouCant Pass Him

### ISSUE THREAD

**Issue by TheBatter666** [gamedev8/js-sfa#16]

**Comment by gamedev8** [comment]
It isn't easy, but he can be beat ;)

If you always block low he will leave himself vulnerable a lot.

**Comment by TheBatter666** [comment]
then let me see a video of you beat sagat

**Comment by gamedev8** [comment]
I beat him a few times here.
https://www.youtube.com/watch?v=Qtl23lgFWP4

**Comment by TheBatter32** [comment]
good job gamedev8
