### ISSUE TITLE
Gamedev you missed some  of the super stuff on the characters 

### ISSUE THREAD

**Issue by TheBatter666** [gamedev8/js-sfa#18]
and here is the link to the video

https://www.youtube.com/watch?v=14AnVI7_JXE

**Comment by gamedev8** [comment]
Yeah I didn't get enough time to finish everything.

**Comment by TheBatter666** [comment]
can you make the new update on it

**Comment by TheBatter32** [comment]
cmon gamedev can you make a mew update

**Comment by gamedev8** [comment]
I would like to finish this game one day, but I don't know when that will be. I'm busy with other projects.

**Comment by gamedev8** [comment]
This is the same issue as  #11  so I'm closing this one.

**Comment by TheBatter32** [comment]
Maybe People Would Like It When You Make The New Update
