### ISSUE TITLE
 I Think Ryu And Ken Are Dead In This Picture

### ISSUE THREAD

**Issue by TheBatter32** [gamedev8/js-sfa#19]
![Screenshot 2022-01-08 12 47 17 AM](https://user-images.githubusercontent.com/93792595/148633217-0f476422-6c82-4abe-9552-ccbb28616b7e.png)

**Comment by TheBatter666** [comment]
yeah me too

**Comment by gamedev8** [comment]
What happened?

**Comment by TheBatter666** [comment]
um i glitched them to die instantly

**Comment by TheBatter32** [comment]
![Screenshot 2022-01-16 12 20 20 AM](https://user-images.githubusercontent.com/93792595/149648354-4d044049-3de6-4c3e-9187-7fd7137c5c12.png)

**Comment by TheBatter32** [comment]
its the american flag
